[references]
buttons = "@common.buttons"

[hero]
title = "Hola Mundo"
description = "Esta es una descripción de la sección hero"
new-key = "This is a new key added to primary locale"

[hero.cta]
sign-up = "{@buttons.sign-up} al sitio web"
login = "{@buttons.login} al sitio web"

[toast]
greeting = "Hello {name}"